export const IOC__SERVICE__NEST_TEMPLATE = 'IOC__SERVICE__NEST_TEMPLATE';
export const IOC__INTERCEPTOR__GRPC_CACHE = 'IOC__INTERCEPTOR__GRPC_CACHE';
export const IOC__CLIENT_PROVIDER__SELF = 'IOC__CLIENT_PROVIDER__SELF';
